import React, { useEffect, useState } from "react";
import {
  Text,
  View,
  StyleSheet,
  FlatList,
  TouchableOpacity,
} from "react-native";

interface ClassTests {
  id: string; // autogenerated by system. or id of the nosql doc
  testName: string;
  date: number;
  marks: number;
  fullMarks: number;
  availableResources: string[]; // array of urls. tutor video, url of question's set uploaded in s3, etc
}

export default function ClassDetailsScreen() {
  const dummyTests: ClassTests[] = [
    {
      id: "id001",
      testName: "",
      date: 1744727190000,
      marks: 40,
      fullMarks: 100,
      availableResources: [],
    },
    {
      id: "id002",
      testName: "",
      date: 1744727190000,
      marks: 40,
      fullMarks: 100,
      availableResources: [],
    },
    {
      id: "id003",
      testName: "",
      date: 1744727190000,
      marks: 40,
      fullMarks: 100,
      availableResources: [],
    },
    {
      id: "id004",
      testName: "",
      date: 1744727190000,
      marks: 40,
      fullMarks: 100,
      availableResources: [],
    },
  ];

  return (
    <View style={styles.container}>
      <Text style={styles.text}>Class Name: {"className"}</Text>
      <Text style={styles.text}>Teacher Name: {"teacherName"}</Text>

      <View style={{ height: 24 }} />

      <FlatList
        // style={{ backgroundColor: "lightgreen" }}
        data={dummyTests}
        showsVerticalScrollIndicator={false}
        // contentContainerStyle={{ paddingHorizontal: 24 }}
        keyExtractor={(item) => item.id}
        ItemSeparatorComponent={() => <View style={{ height: 12 }} />}
        renderItem={({ item }) => (
          <TouchableOpacity
            style={{
              height: 48,
              width: "100%",
              backgroundColor: "white",
              borderRadius: 8,
            }}
          />
        )}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#25292e",
    padding: 24,
    // justifyContent: "center",
    // alignItems: "center",
  },
  text: {
    color: "#fff",
  },
});
