import { useLocalSearchParams, useNavigation } from "expo-router";
import React, { useEffect, useLayoutEffect, useState } from "react";
import {
  Text,
  View,
  StyleSheet,
  FlatList,
  TouchableOpacity,
} from "react-native";

interface ClassTests {
  id: string; // autogenerated by system. or id of the nosql doc
  testName: string;
  date: number;
  marks: number;
  fullMarks: number;
  availableResources: string[]; // array of urls. tutor video, url of question's set uploaded in s3, etc
}

export default function ClassDetailsScreen() {
  const navigation = useNavigation();
  const { id, title } = useLocalSearchParams();
  const dummyTests: ClassTests[] = [
    {
      id: "id001",
      testName: "Math Mid Term test",
      date: 1744727190000,
      marks: 60,
      fullMarks: 100,
      availableResources: [],
    },
    {
      id: "id002",
      testName: "Science Mid Term test",
      date: 1744727190000,
      marks: 58,
      fullMarks: 100,
      availableResources: [],
    },
    {
      id: "id003",
      testName: "Math Final test",
      date: 1744727190000,
      marks: 88,
      fullMarks: 100,
      availableResources: [],
    },
    {
      id: "id004",
      testName: "Math 2 Final test",
      date: 1744727190000,
      marks: 60,
      fullMarks: 100,
      availableResources: [],
    },
  ];

  useLayoutEffect(() => {
    if (navigation && title) {
      navigation.setOptions({ title: title });
    }
  });

  return (
    <View style={styles.container}>
      <View style={{ height: 48 }} />
      <Text style={styles.text}>Class Name: {"<class-name>"}</Text>
      <Text style={styles.text}>Teacher Name: {"<teacher-name>"}</Text>

      <View style={{ height: 24 }} />

      <FlatList
        // style={{ backgroundColor: "lightgreen" }}
        data={dummyTests}
        showsVerticalScrollIndicator={false}
        // contentContainerStyle={{ paddingHorizontal: 24 }}
        keyExtractor={(item) => item.id}
        ItemSeparatorComponent={() => <View style={{ height: 12 }} />}
        renderItem={({ item }) => (
          <TouchableOpacity
            style={{
              // height: 48,
              width: "100%",
              backgroundColor: "white",
              borderRadius: 8,
              justifyContent: "center",
              paddingHorizontal: 24,
              paddingVertical: 8,
            }}
          >
            <Text>
              {item.testName} : {item.marks}/{item.fullMarks}%
            </Text>

            <View style={{ height: 12 }} />

            <Text>Test date: {new Date(item.date).toUTCString()}</Text>
          </TouchableOpacity>
        )}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#25292e",
    padding: 24,
    // justifyContent: "center",
    // alignItems: "center",
  },
  text: {
    color: "#fff",
  },
});
